version: '2'
services:
    web:
        build: .
        container_name: "flask"
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis-db
        links:
            - redis-db

    redis-db:
        image: "redis:latest"
        container_name: "redis"
        ports:
            - "6379:6379"